name: "build-be"
description: "Build and push backend Docker image"
inputs:
  CICD_SA_GCP_JSON_KEY:
    description: 'Json key to GCP SA'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v0.8.2'
      with:
        credentials_json: '${{ inputs.CICD_SA_GCP_JSON_KEY }}'

    - name: Build, tag and push Docker image
      shell: bash
      run: |
        ./infra/scripts/push_images.sh backend
