version: '3.8'

services:
  backend:
    image: backend
    platform: linux/amd64
    build:
      context: .
      dockerfile: src/backend/Dockerfile
      target: test
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: 0.5
        reservations:
          memory: 128m
          cpus: 0.25

  postgres:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=ingoodhands
      - POSTGRES_DB=in_good_hands
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: 0.5
        reservations:
          memory: 128m
          cpus: 0.25

volumes:
  pgdata: