version: '3.8'

services:
  backend:
    image: backend
    platform: linux/amd64
    build:
      context: .
      dockerfile: src/backend/Dockerfile
      args:
        APP: WebApi

  worker:
    image: worker
    platform: linux/amd64
    build:
      context: .
      dockerfile: src/backend/Dockerfile
      args:
        APP: Worker
