version: '3.8'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=ingoodhands

volumes:
  pgdata: