version: '3.8'

services:
  frontend:
    image: frontend
    platform: linux/amd64
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    ports:
     - "80:80"

  backend:
    image: backend
    platform: linux/amd64
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
     - "5000:5000"

  postgres:
    image: postgres:14
    platform: linux/amd64
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=ingoodhands
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: 0.5
        reservations:
          memory: 128m
          cpus: 0.25

volumes:
  pgdata: