version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=ingoodhands
      - POSTGRES_DB=in_good_hands
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 128m

