version: '3.8'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    ports:
     - "80:80"

  backend:
    image: backend
    build:
      context: .
      dockerfile: src/backend/Dockerfile

  postgres:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=ingoodhands

volumes:
  pgdata: