name: "Backend tests"
description: "Run backend integration and unit tests"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Set variables for testing
      run: |
        echo "DB_HOST=localhost" >> $GITHUB_ENV
        echo "DB_USER=postgres" >> $GITHUB_ENV
        echo "DB_PASSWORD=ingoodhands" >> $GITHUB_ENV
        echo "DB_DATABASE=in_good_hands" >> $GITHUB_ENV
        echo "DB_PORT=5432" >> $GITHUB_ENV
        echo "OAUTH2_AUTHORITY=dummy" = >> $GITHUB_ENV
        echo "OAUTH2_AUDIENCE=dummy" = >> $GITHUB_ENV
        echo "OAUTH2_CLIENT_ID=dummy" = >> $GITHUB_ENV
        echo "OAUTH2_SCOPES=dummy" = >> $GITHUB_ENV
        echo "FRONTEND_URL=dummy" = >> $GITHUB_ENV
        echo "HASHIDS_SALT=dummy" = >> $GITHUB_ENV
      shell: bash

    - name: Run backend and postgres for testing
      run: |
        docker-compose -f docker-compose.ci.yml up -d
      shell: bash

    - name: Run tests
      run: |
        dotnet test --collect:"XPlat Code Coverage" --results-directory ./coverage -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      shell: bash
      working-directory: src/backend

    - name: Upload fe artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: src/backend/coverage
