name: "test-int-bet"
description: "Run integration tests"
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2
        #v2 action because v3 causes problem with dotnet containers
        shell: bash

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0.8.2'
        with:
          credentials_json: '${{ secrets.CICD_SA_GCP_JSON_KEY }}'

      - name: Auth to docker registry
        run: |
          gcloud auth configure-docker europe-docker.pkg.dev
        shell: bash

      - name: Run backend and postgres for testing
        run: |
          docker-compose -f docker-compose.ci.yml up -d
        shell: bash

      - name: Exec into backend container and run tests
        run: |
          docker exec ingoodhands_backend-test_1 dotnet test
        shell: bash
