name: "SonarCloud"
description: "Run sonar analysis"
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3

      - name: Set variables for testing
        run: |
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=ingoodhands" >> $GITHUB_ENV
          echo "DB_DATABASE=in_good_hands" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
        shell: bash

      - name: Run backend and postgres for testing
        run: |
          docker-compose -f docker-compose.ci.yml up -d
        shell: bash

      - name: Run tests
        run: |
          coverlet ./AuthServiceTests/bin/Debug/net7.0/AuthServiceTests.dll \
            --target "dotnet" \
            --targetargs "test --no-build" \
            -f=opencover \
            -o="coverage.xml"
        shell: bash
        working-directory: src/backend

      - uses: actions/upload-artifact@v3
        if: always() && !cancelled()
        with:
          name: test-reports
          path: |
            coverage.xml
        working-directory: src/backend
