name: "Build and push backend Docker image"

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  build-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0.8.2'
        with:
          credentials_json: '${{ secrets.CICD_SA_GCP_JSON_KEY }}'

      - name: Build, tag and push backend Docker image
        run: |
          ./infra/scripts/push_images.sh backend

      - name: Build, tag and push int-tests Docker image
        run: |
          ./infra/scripts/push_images.sh backend-test test
