name: "Build, test and push Docker image"

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  check-changed-paths:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - 'src/frontend/**'
            backend:
              - 'src/backend/**'
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}

  build-be:
    if: ${{ needs.check-changed-paths.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-be

  test-be:
    if: ${{ needs.check-changed-paths.outputs.backend == 'true' }}
    needs:
      - build-be
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-be

  build-fe:
    if: ${{ needs.check-changed-paths.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-fe
