name: "Build deploy to Firebase"

on:
  push:
    branches:
      - main
    paths:
      - 'src/frontend/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE: ${{ inputs.service }}
    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.8.2'
        with:
          credentials_json: '${{ secrets.CICD_SA_GCP_JSON_KEY }}'

      - name: Generate env variables and login to Firebase
        run: |
          echo "${{ secrets.CICD_SA_GCP_JSON_KEY }}" > gcloud.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${PWD}/gcloud.json" >> GITHUB_ENV

      - name: Install dependencies, build and deploy to Firebase
        run: |
          cd ./src/frontend
          
          npm i -g @angular/cli

          npm install -g firebase-tools
          
          npm ci

          ng build --configuration=production
          
          cd ../..
          
          firebase deploy     
          
         
