name: "Build, test and push Docker image"

on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  check-changed-paths:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - 'src/frontend/**'
            backend:
              - 'src/backend/**'
            workflow:
              - '.github/**'
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}
      workflow: ${{ steps.changes.outputs.workflow }}

  build-be:
    if: ${{ needs.check-changed-paths.outputs.backend == 'true'  || needs.check-changed-paths.outputs.workflow == 'true' }}
    runs-on: ubuntu-latest
    needs:
      - check-changed-paths
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-be
        with:
          CICD_SA_GCP_JSON_KEY: ${{ secrets.CICD_SA_GCP_JSON_KEY }}

  test-be:
    if: ${{ needs.check-changed-paths.outputs.backend == 'true' || needs.check-changed-paths.outputs.workflow == 'true' }}
    runs-on: ubuntu-latest
    needs:
      - check-changed-paths
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-int-be

  build-fe:
    if: ${{ needs.check-changed-paths.outputs.frontend == 'true' || needs.check-changed-paths.outputs.workflow == 'true' }}
    runs-on: ubuntu-latest
    needs:
      - check-changed-paths
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-fe

  sonar:
    if: ${{ needs.check-changed-paths.outputs.frontend == 'true' || needs.check-changed-paths.outputs.frontend == 'true' || needs.check-changed-paths.outputs.workflow == 'true' }}
    runs-on: ubuntu-latest
    needs:
      - check-changed-paths
      - test-be
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sonar
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
