name: "Build and upload frontend artifact"

on:
  push:
    branches:
      - main
    paths:
      - 'src/frontend/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE: ${{ inputs.service }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies, build
        run: |          
          npm i -g @angular/cli

          npm install -g firebase-tools
          
          npm ci

          ng build --configuration=production
        working-directory: src/frontend

      - name: Compress fe build files
        run: tar -cvf fe_artifact.tar ./dist
        working-directory: src/frontend

      - name: Upload fe artifact
        uses: actions/upload-artifact@v3
        with:
          name: fe-artifact
          path: src/frontend/fe_artifact.tar