name: "Build deploy Docker image"

on:
  workflow_dispatch:
    inputs:
      service:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

