name: "Frontend deploy"

on:
  push:
    branches:
      - main
    paths:
      - 'src/frontend/**'
      - '.github/**'
      - 'firebase.json'

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    env:
      SERVICE: ${{ inputs.service }}
    steps:
      - uses: actions/checkout@v3

      - name: Download fe artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-test-all.yml
          name: fe-artifact
          path: .
          workflow_conclusion: ""

      - name: Untar fe artifact
        run: tar -xvf fe_artifact.tar -C src/frontend

      - name: Install firebase
        run: |
          npm install -g firebase-tools

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.8.2'
        with:
          credentials_json: '${{ secrets.CICD_SA_GCP_JSON_KEY }}'

      - name: Generate env variables and login to Firebase
        run: |
          echo "${{ secrets.CICD_SA_GCP_JSON_KEY }}" > gcloud.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${PWD}/gcloud.json" >> GITHUB_ENV

      - name: Deploy to Firebase
        run: |
          firebase deploy     

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: src/frontend
