name: "Deploy backend Docker image"

on:
  push:
    branches:
      - main
    paths:
      - 'src/backend/**'
  workflow_dispatch:


permissions:
  contents: read
  id-token: write

jobs:
  deploy-be:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0.8.2'
        with:
          credentials_json: '${{ secrets.CICD_SA_GCP_JSON_KEY }}'

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          region: 'europe-west1'
          service: 'backend'
          image: 'europe-docker.pkg.dev/indagoodhandsdev/default-docker/backend'
