name: "Deploy fe to Firebase"

on:
  push:
    branches:
      - main
    paths:
      - 'src/frontend/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE: ${{ inputs.service }}
    steps:
      - uses: actions/checkout@v3

      - name: Download fe artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: fe-artifact
          path: .

      - name: Untar fe artifact
        run: tar -xvf fe_artifact.tar -C src/frontend

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.8.2'
        with:
          credentials_json: '${{ secrets.CICD_SA_GCP_JSON_KEY }}'

      - name: Generate env variables and login to Firebase
        run: |
          echo "${{ secrets.CICD_SA_GCP_JSON_KEY }}" > gcloud.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${PWD}/gcloud.json" >> GITHUB_ENV

      - name: Deploy to Firebase
        run: |
          firebase deploy     
          
         
