name: "Run integration tests"

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  test-int:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        #v2 action because v3 causes problem with dotnet containers

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0.8.2'
        with:
          credentials_json: '${{ secrets.CICD_SA_GCP_JSON_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Auth to docker registry
        run: |
          gcloud auth configure-docker europe-docker.pkg.dev

      - name: Auth to docker registry
        shell: pwsh
        run: |
          & $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon

      - name: Run backend and postgres for testing
        run: |
          docker-compose -f docker-compose.ci.yml up -d --build

      - name: Exec into backend container and run tests
        run: |
          docker exec ingoodhands_backend-test_1 dotnet test
